model:
  start_token: spacegroup_number
  cascade:
    order:
      - elements
      - site_symmetries
      - sites_enumeration
      - multiplicity
    embedding_size:
      elements: 40
      site_symmetries: 40
      sites_enumeration: 16
      multiplicity: 0
  WyckoffTrainer_args:
    multiclass_next_token_with_order_permutation: false
    target: Scalar
    target_name: gene_min_formation_energy_per_atom
    scalar_loss: mse
    evaluation_samples: 1
    train_batch_size: 12500
    val_batch_size: 12500
    test_batch_size: 12500
    compile_model: true
  CascadeTransformer_args:
    start_type: one_hot
    perceptron_shape: pyramid
    concat_token_counts: false
    concat_token_presence: false
    aggregate_after_encoder: true
    mixer_layers: 1
    token_aggregation: weighted_mean
    aggregation_weight: 3
    include_start_in_aggregation: false
    aggregation_inclsion: aggr
    outputs: 1
    num_fully_connected_layers: 3
    learned_positional_encoding_max_size: 0
    learned_positional_encoding_only_masked: true
    TransformerEncoderLayer_args:
      nhead: 4
      dim_feedforward: 320
      dropout: 0.0
    TransformerEncoder_args:
      num_layers: 3
      enable_nested_tensor: false
optimisation:
  optimiser:
    name: AdamW
    config:
      lr: 0.003
      weight_decay: 0.01
      betas: [0.9, 0.999]
  scheduler:
    module: wyckoff_transformer.schedules
    name: warmup_stable_decay
    config:
      warmup_fraction: 0.002
      decay_fraction: 0.2130
      final_lr_fraction: 0.0
      decay_shape: 1-sqrt
  validation_period: 250
  early_stopping_patience_epochs: 1000000
  clip_grad_norm: 10.0
  epochs: 2859
tokeniser:
  name: der_tokenizer_v1
evaluation:
  n_structures_to_generate: 10000
