model:
  start_token: spacegroup_number
  cascade:
    order:
      - elements
      - site_symmetries
      - sites_enumeration
      - multiplicity
    is_target:
      elements: true
      site_symmetries: true
      sites_enumeration: true
      multiplicity: false
    embedding_size:
      elements: 16
      site_symmetries: 16
      sites_enumeration: 7
      multiplicity: null
  WyckoffTrainer_args:
    multiclass_next_token_with_order_permutation: true
    target: NextToken
    evaluation_samples: 100
  CascadeTransformer_args:
    perceptron_shape: pyramid
    concat_token_counts: false
    concat_token_presence: true
    aggregate_after_encoder: false
    mixer_layers: 1
    token_aggregation: sum
    include_start_in_aggregation: false
    aggregation_inclsion: concat
    outputs: token_scores
    num_fully_connected_layers: 3
    learned_positional_encoding_max_size: 0
    learned_positional_encoding_only_masked: true
    TransformerEncoderLayer_args:
      nhead: 4
      dim_feedforward: 256
      dropout: 0.2
    TransformerEncoder_args:
      num_layers: 3
      # Nested tensors are broken in the current version of PyTorch
      # https://github.com/pytorch/pytorch/issues/97111
      # We also don't need them as we ensure that batches all have the same length in WychoffTrainer
      enable_nested_tensor: false
optimisation:
  optimiser:
    name: SGD
    config:
      lr: 0.2
  scheduler:
    name: ReduceLROnPlateau
    config:
      factor: 0.8
      # note that scheduler is called every validation_period epochs
      patience: 20
  validation_period: 1000
  early_stopping_patience_epochs: 100000
  clip_grad_norm: 2.
  epochs: 1000000
tokeniser:
  name: mp_20_CSP
evaluation:
  n_structures_to_generate: 10000
