[tool.poetry]
name = "wyckofftransformer"
version = "0.2.0"
description = ""
authors = ["Nikita Kazeev <kazeevn@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<=3.12"
pymatgen = ">=2023.10.4"
ipykernel = ">=6.25.2"
pandas = ">=2.1.1"
numpy = ">=1.26.0"
ase = ">=3.22.1"
nglview = ">=3.0.8"
torch = "==2.4.0a0+gitda7bf1d"
#torchvision = ">=0.16.0"
#torchaudio = ">=2.2.0"
wandb = ">=0.16.0"
#torchviz = ">=0.0.2"
#torch-uncertainty = ">=0.1.5"
py3dmol = ">=2.0.4"
pyxtal = ">=0.6.6"
#pyxtal = {git = "https://github.com/qzhu2017/PyXtal.git", rev = "master"}
#intel-extension-for-pytorch = "^2.3.0"
#oneccl-bind-pt = {version = "^2.3.0+cpu", source = "pytorch-intel-cpu"}


[[tool.poetry.source]]
name = "pytorch-intel-cpu"
url = "https://pytorch-extension.intel.com/release-whl/stable/cpu/us/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
