model:
  start_token: spacegroup_number
  cascade:
    order:
      - elements
      - site_symmetries
      - harmonic_cluster
      - harmonic_site_symmetries
    is_target:
      elements: true
      harmonic_cluster: true
      site_symmetries: true
      harmonic_site_symmetries: false
    embedding_size:
      elements: 16
      site_symmetries: 12
      # In principle, harmonic_site_symmetries should be enough
      harmonic_cluster: 4
      harmonic_site_symmetries:
        pass_through_vector: 12
    # Augmented fields are sampled at matching indices
    augmented:
      - harmonic_cluster
      - harmonic_site_symmetries
  WyckoffTrainer_args:
    multiclass_next_token_with_order_permutation: true
    target: NextToken
    evaluation_samples: 100
    train_batch_size: null
    compile_model: false
  CascadeTransformer_args:
    start_type: one_hot
    perceptron_shape: pyramid
    compile_perceptrons: false
    concat_token_counts: false
    # TODO enable
    concat_token_presence: false
    aggregate_after_encoder: false
    mixer_layers: 1
    token_aggregation: null
    include_start_in_aggregation: false
    aggregation_inclsion: null
    outputs: token_scores
    num_fully_connected_layers: 3
    learned_positional_encoding_max_size: 0
    learned_positional_encoding_only_masked: true
    #prediction_perceptron_dropout: 0.01
    #emebdding_dropout: 0.01    
    TransformerEncoderLayer_args:
      nhead: 4
      dim_feedforward: 128
      dropout: 0.2
    TransformerEncoder_args:
      num_layers: 3
      enable_nested_tensor: false
optimisation:
  optimiser:
    module: schedulefree
    name: SGDScheduleFree
    config:
      lr: 0.2
  validation_period: 1000
  early_stopping_patience_epochs: 100000
  clip_grad_norm: 2.
  epochs: 1000000
tokeniser:
  name: with_stop/augmented/harmonic_cluster
evaluation:
  n_structures_to_generate: 1100
